### ISSUE TITLE
Crear issues de Obrir Projecte i Tancar Projecte tal i com hi ha a Carpeta o PortaFIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#1]
Crear issues de Obrir Projecte i Tancar Projecte tal i com hi ha a Carpeta o PortaFIB

**Comment by fbosch-fundaciobit** [comment]
S'han creat els issues d'obrir i tancar versió:

- https://github.com/Fundacio-Bit/enviafib/issues/2

- https://github.com/Fundacio-Bit/enviafib/issues/3
