### ISSUE TITLE
Amagar pipelles per Rols User

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#105]
Els usuaris amb NOMÉS rol user no han de veure CAP pipella ( de "Admin", "Web DB" etc...). Unicament han de veure el contingut de la pipella d'usuaris,

![image](https://user-images.githubusercontent.com/40387703/176392583-f4075589-6153-4897-b33c-02e8e4e79f46.png)

**Comment by fbosch-fundaciobit** [comment]
S'han amagat totes les pipelles menys la de "user" per el rol usuari a l'issue #113. S'ha de comprovar si a mes fa falta amagar la pipella "user", i que no aparegui cap pipella.

**Comment by anadal-fundaciobit** [comment]
Això no era lo que volia en Toni Trobat !!!! En Toni lo que volia era que TOTES les pipelles havien de desapareixer !!!!!!

**Comment by anadal-fundaciobit** [comment]
Solucionat !!!!
