### ISSUE TITLE
El boto d'enviar peticions per email ha d'aparèixer a peticions de flux i autofirma també

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#106]
El botó d'enviar per email s'ha de mostrar a totes les peticions finalitzades amb un document firmat dins la petició.

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/176658516-65540a17-67d8-4476-93a5-e30f914b72e5.png)
