### ISSUE TITLE
Chrome bloqueja la pantalla emergent del plugin d'autofirma

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#108]
Pareix que en alguns casos, Google Chrome bloqueja la finestra emergent de autofirma. S'ha de revisar perque passa i si es pot solventar/prevenir.

**Comment by anadal-fundaciobit** [comment]
Solucionat. Arreglat FLux i AutoFIrma ja que tots dos tenien el mateix problema.
