### ISSUE TITLE
Apareixen missatges d'error duplicats

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#109]
A les pantalles de creació de peticions de firma, algunes mostren el missatge de error de que falta adjuntar un fitxer 2 vegades (un damunt l'altre). S'ha de corregir i que es mostri domes 1.

![imagen](https://user-images.githubusercontent.com/17084256/176673773-39552855-cec1-40ef-a6a0-628be50e0486.png)

**Comment by ptrias-fundaciobit** [comment]
Es fa la validació 2 pics.

Persistencia
persistence.validator.PeticioValidator.java : line 262
genapp.generator.JPAValidatorGenerator.java : line 213

Back
back.validator.webdb.PeticioWebValidator.java : line 95
genapp.generator.BackGenerator.java : line 334

**Comment by ptrias-fundaciobit** [comment]
https://github.com/GovernIB/genapp/commit/ca2a81544ea4d8ae4de9b9c081a964e2fe0f5b41

**Comment by ptrias-fundaciobit** [comment]
Solucionat:

**Comment by ptrias-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/95921330/180994740-80d1e937-7d31-4ce0-b453-51602a4ee637.png)

**Comment by ptrias-fundaciobit** [comment]
hola
