### ISSUE TITLE
Canvi de literals al menú lateral esquerr.

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#112]
Les opcions del menú esquerr han de tenir els seguents literals:

 - Autofirma
 - Enviar firma per NIF
 - Firma personalitzada    (Actualment firma per flux)
 - Enviar a firmar al/a la director/a
 - Enviar a firmar al/a la secretari/a

**Comment by anadal-fundaciobit** [comment]
Solucionat.
