### ISSUE TITLE
Comprovar si s'ha definit correctament JNDI d'emails

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#115]
(1) revisar si llegir el JNDI de correus es correcte. S'ha de fer disn de ServletInit del BAck.

(2) Comprovar si el servidor de correu està actiu emprant el següent codi: 
https://stackoverflow.com/questions/3060837/validate-smtp-server-credentials-using-java-without-actually-sending-mail
No s'han d'utilitzar contrasenyes !!! el session s'ha d'obtenir del nom JNDI.

**Comment by fbosch-fundaciobit** [comment]
S'ha gordat un "stash" de Git en local amb els canvis, però no se com connectar amb el JNDI sense emprar contrasenyes. Queda pendent de revisar.

**Comment by ptrias-fundaciobit** [comment]
Solucionat. Ara surt un missatge al server.log quan hi ha un error amb la configuració del correu
