### ISSUE TITLE
Surt Default quan intentes enviar el document signat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#116]
Surt Default quan intentes enviar el document signat

![imagen](https://user-images.githubusercontent.com/17084256/176668183-d954a503-c64b-4421-92ed-7602f5a1fa94.png)

A més si deixes el camp buit del email surt aquest error:

![imagen](https://user-images.githubusercontent.com/17084256/176668714-eb478ca6-fc9d-4c1a-af93-03c20033d6a0.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha corregit l'error. Sies deixa buit el "textbox" apareix un missatge d'alerta:

![image](https://user-images.githubusercontent.com/40387703/178441532-aaba21e1-bb8d-4553-a047-63a1118ed8e0.png)
