### ISSUE TITLE
Revisar llicència origen de Logo i Favicon

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#117]
Revisar llicència d'ús de la pàgina web d'on s'ha tret el Logo i el Favicon:
   * Logo: https://www.freepng.es/png-k70be6/
   * Favicon:  https://iconos8.es/icons/set/firma--orange

**Comment by ptrias-fundaciobit** [comment]
Al tractarse d'un producte Opensource, no hi ha cap problema. Acceptam les dues imatges (logo i Favicon)
