### ISSUE TITLE
Substituir logo de FundacióBit per logo de CAIB en capçalera i peu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#118]
Substituir logo de FundacióBit per logo de CAIB en capçalera i peu: https://www.caib.es/sites/manualdidentitatcorporativa/es/govern_de_les_illes_balears/

IMPORTANT: S'han de mantenir les mateixes mesures/dimensions  de les imatges originals.

![imagen](https://user-images.githubusercontent.com/17084256/176671283-a96b9ecb-fe17-452b-a693-ab8c69179fd9.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/176890191-b9d7e342-e6c0-4f5e-bf2f-ab69651a89b9.png)
