### ISSUE TITLE
Canviar nom del menú del ROLE USER

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#120]
(1) Canviar nom del menú del ROLE USER
(2) Eliminar la Barra marcada en verd 

![imagen](https://user-images.githubusercontent.com/17084256/176842873-ed76e16e-f6d7-4c89-9fab-ee689ee334d9.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/176890374-8f839f3a-9fbd-4db2-838e-40d8998f9a54.png)
