### ISSUE TITLE
Arreglar pàgina de Confirmació de Flux de Firmes

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#122]
Arreglar pàgina de Confirmació de Flux de Firmes:
(1) Posar color als botons "continuar" (PRIMARY) i "cancelar" (GRIS): https://getbootstrap.com/docs/4.0/components/buttons/
(2) Canviar la cadena "Validació del Flux" per "Confirmació del Flux" del wizard
(3) Separar els botons "continuar" i "cancelar"  del iframe de Veure Flux de Firmes

![imagen](https://user-images.githubusercontent.com/17084256/176854747-6207e516-6d24-470d-ad06-0e7f802c7392.png)

**Comment by fbosch-fundaciobit** [comment]
Punts 1 i 2 fets:

![image](https://user-images.githubusercontent.com/40387703/177295390-4c923587-9b61-4040-acc1-6d6fe3df6495.png)
