### ISSUE TITLE
Revisar menus seleccionats en negreta

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#123]
Revisar totes les opcions del menú d'usuari per a que quan es selecciona certa opció es mantengui en negreta durant tot el procés de la petició.

![imagen](https://user-images.githubusercontent.com/17084256/176855510-497202a6-c4a7-4b98-b73f-f6f1a3384f50.png)

**Comment by fbosch-fundaciobit** [comment]
Revisat. S'han corregit els menus de Firma a director i a secretari.
