### ISSUE TITLE
Arreglar warning d'Eclipse: hostUrl is not used.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#124]
Arreglar warning d'Eclipse: hostUrl is not used.

![imagen](https://user-images.githubusercontent.com/17084256/176878231-89104c51-fa99-4f5e-b6f3-51a58069799c.png)

**Comment by fbosch-fundaciobit** [comment]
Arreglats warning de compilació:

![image](https://user-images.githubusercontent.com/40387703/177284626-227c4231-e946-44c1-836f-c11eb4fdc3a1.png)
