### ISSUE TITLE
Estat de Petició ha de ser de tipus integer en java i bbdd

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#125]
Estat de Petició ha de ser de tipus integer en java i bbdd

**Comment by fbosch-fundaciobit** [comment]
S'ha canviat el tipus a BBDD, i s'ha regenerat el codi i testejat l'apicació. Pereix que tot funciona correctament.

![2022-07-12_14h41_38](https://user-images.githubusercontent.com/40387703/178492205-c88a969e-0019-4789-9ce2-f3430932a22c.png)
