### ISSUE TITLE
Afegir botó de visualització de document firmat al llistat de peticions

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#126]
S'ha d'afegir de nou el botó per visualitzar el document un cop ha sigut firmat, des de la llista de peticions:

![image](https://user-images.githubusercontent.com/40387703/177325008-1780690c-aecb-420c-adf7-6f8ab1384696.png)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
![imagen](https://user-images.githubusercontent.com/17084256/177502618-9647c649-ed63-45bc-b03c-cc15cc51969c.png)
