### ISSUE TITLE
Millores pàgina de presentació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#127]
(1) Revisar text de la pàgina de presentació: 
            - QUE ES ENVIAFIB?
            - Retorn de carro en la segona frase.

![imagen](https://user-images.githubusercontent.com/17084256/177522440-0303e00c-59d9-499e-900a-f455acd1e8e4.png)

(2) Afegir una nova opció al final del menú d'usuari que sigui "About-...". Ha de mostrar la pàginade presentació( o home). Només ha d'apareixer quan NOMES es tengui el ROLE_USER. Implementació: 
            - Afegir un tile derivat de user que apunti a home.jsp
            - Afegir un requestmapping per exemple dins LlistadePeticionsUserController

**Comment by fbosch-fundaciobit** [comment]
S'han afegit les millores llistades:

![image](https://user-images.githubusercontent.com/40387703/177751811-e66b1ef1-7a9a-4c7d-82b4-4087c36ec5e1.png)
