### ISSUE TITLE
Fer proves d'una pàgina per pujar un o varis fitxers emprant drag&drop

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#128]
Fer proves d'una pàgina per pujar un o varis fitxers emprant drag&drop. En un futur servirà com a pas previ en tots els tipus de peticions. Temporalment es guardaran els fitxers en sessió. 

(1) Crear un pàgina JSP com la que mostren les captures de més abaix
(2) Un cop pitjat ok, Crear la part de servidor (Request de Controller) que reculli els fitxers (POST) i els guardi en directori temporal i la informació disn la session (request.getSession)
(3) Al final del punt (2) es redireccionarà a una segona pàgina (JSP) que mostri els fitxers pujats i links per descarregar-los

PD1: NOMES s'HA DE FER AIXÒ. RES MES.
PD2: Dins Github FundacioBit PinalAdmin hi ha el codi de de pujada de fitxers (no se si es exactament això)

![imagen](https://user-images.githubusercontent.com/17084256/177539068-16d6bce9-7ceb-488d-b3df-138e50a0d903.png)

![imagen](https://user-images.githubusercontent.com/17084256/177538706-c143fa18-a817-46ab-9599-09c35d5e78b0.png)

**Comment by ptrias-fundaciobit** [comment]
Punt 1 fet correctament. Els punts dos i tres queden pendents per quan torni @anadal-fundaciobit 
![image](https://user-images.githubusercontent.com/95921330/179967649-bc66fe60-ccb1-4b20-8e6b-6523f1d1113a.png)

**Comment by ptrias-fundaciobit** [comment]
Finalitzat
