### ISSUE TITLE
Afegir pantalla per mostrar dades del document Arxivat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#134]
Tal i com es fa amb el SignatureInfo a vista de Petició, s'ha de fer el mateix per InfoArxiu:

(1)  Duplicar un Controlador nou derivat de InfoArxiu que només tengui Vista (no list, no edit, no new, no delete). Al cancel·lar que torni a la petició.
(2) Afegir boto a Vista de Petició que apunti a Info Arxiu (només si aquesta té informació d'arxiu)

**Comment by fbosch-fundaciobit** [comment]
Afegida pantallla per mostrar la informació d'arxivat:

![image](https://user-images.githubusercontent.com/40387703/182832488-1198d1fe-0731-4af0-8347-ba098609565b.png)
