### ISSUE TITLE
Gestió de grups d'usuaris

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#135]
(1) Afegir una taula de Grups d'usuaris (grupid, nom i descripció).
(2) Una segona taula que faci d'enllaç entre Grups i Usuaris anomenada GrupUsuari: grupusuariid, usuariid, grupid
NOTA: S'ha d'afegir un UNIQUE de (usuariid, grupid)
(3) Afegir una opció a menú administrador per gestionar grups
(4) Afegir boto per afegir usuaris a grups (es farà de forma simple cridant al new de un Controller de GrupUsuari )

**Comment by ptrias-fundaciobit** [comment]
Fet:
![image](https://user-images.githubusercontent.com/95921330/182349930-8a74d6f3-3d03-478d-81e2-6222b3ba4e98.png)
![image](https://user-images.githubusercontent.com/95921330/182349974-e0285d34-6b58-47c8-ab98-73244612f633.png)
