### ISSUE TITLE
Els usuaris amb ROLE_ADMIN no poden entrar a EnviaFIB

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/enviafib#140]
![image](https://user-images.githubusercontent.com/95921330/182349692-9808082a-19bd-4d51-853a-209670b6e947.png)

**Comment by fbosch-fundaciobit** [comment]
Els usuaris amb rol Admin ja poden entrar:

![image](https://user-images.githubusercontent.com/40387703/183066814-872858ec-b769-4f58-82f2-4bf16496c396.png)

**Comment by anadal-fundaciobit** [comment]
NO TE LA PIPELLA  D'INICI   !!!!!!!

**Comment by fbosch-fundaciobit** [comment]
Ja es veu el menú d'inici com a administrador i com a usuari:

![image](https://user-images.githubusercontent.com/40387703/183393633-ab74fc90-3eae-4677-a3a4-a4e3e4d83813.png)
