### ISSUE TITLE
Gestió de PLugins de Estructura Organitzativa

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#142]
En el issue "Implementar Plugin d'Estructura organitzativa #141"  es va implementar una API i un PLugin per la gestió dels Càrrecs d'una organització. Ara s'ha d'utilitzar dins d'EnviaFIB: 
(1) Gestionar el Plugin emprant BBDD. Afegir Pantalla al menú d'Administrador. Revisar DigitalIB com ho implementa (capa Logic i  BACK) 
(2) Utilitzar en les peticions de firma a Director General i Secretari.

**Comment by ptrias-fundaciobit** [comment]
Solucionat
