### ISSUE TITLE
Errors de BBDD al Actualitzar el Projecte amb GenAPP

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#144]
Errors de BBDD al Actualitzar el Projecte amb GenAPP

![image](https://user-images.githubusercontent.com/17084256/182381230-ae831fae-3141-4483-a53a-206a6362d748.png)

**Comment by fbosch-fundaciobit** [comment]
S'han crat els indexos:

![image](https://user-images.githubusercontent.com/40387703/182843264-cccd13a5-c50f-474a-b497-c5bc6e193056.png)
