### ISSUE TITLE
Millorar avís de no càrrec i no permetre si no hi ha Plugin Estructura organitzativa

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#146]
(1) AVIS: Ha d'informar i proposar solució. S'ha de pensar amb l'usuari final i aquest no entendrà el missatge. Proposta: "No s´ha pogut esbrinar Cap d'Àrea o  Director General de la seva Unitat. Posis en contacte amb el seu Administrador i comenti que no hi ha cap Plugin d'Estructura Organitzativa actiu". Canviar missatges a tipus d'error 
(2) Ara hi ha el Plugin d'Estructura Organitzativa que controla els càrrecs. Si aquest no es poden averiguar llavors aquesta opció no s'ha de mostrar. Tornar al llistat.

![imatge](https://user-images.githubusercontent.com/17084256/183577585-d32e3f0a-ab13-4ed2-98db-8485a53d950b.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat

**Comment by ptrias-fundaciobit** [comment]
(1) Crear una classe AbtractFirmaCarrecUserController que contengui el codi de  FirmaSecretariUserController ambun mètode abstract getCarrec() i estengui de AbstractFirmaUserController.
(2) Renombrar  FirmaSecretariUserController  per  FirmaCarrecSecretariUserController  i fer-ho estendre de  AbtractFirmaCarrecUserController 
 (3) Renombrar  FirmaDirectorUserController  per  FirmaCarrecDirectorUserController  i fer-ho estendre de  AbtractFirmaCarrecUserController

**Comment by ptrias-fundaciobit** [comment]
Solucionat
