### ISSUE TITLE
Obtenir Codi Dir3 del Funcionari a partir del Plugin d'Estructura Organitzativa

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#147]
Obtenir Codi Dir3 del Funcionari a partir del Plugin d'Estructura Organitzativa i ocultar-ho en la pantalla de Nova Petició de Firma.

S'ha de controlar que existeixi un Plugin d'Estructura organitzativa i que el valor retornat per aquest no sigui null o buit.

![imatge](https://user-images.githubusercontent.com/17084256/183579429-72f4fe1b-f0b4-4cb8-baf2-224119a1ce09.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat
