### ISSUE TITLE
Millorar test de Plugin d'Estructura organitzativa

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#148]
(1) S'han de provar tots els mètodes de l'API i mostrar informació obtinguda. Millorar el que hi ha.
(2) Quan s'espitgi el boto de test ha d'aparèixer un diàleg ( prompt() en javaScript) amb l'username que ha fet login per defecte però que l'usuari administrador pugui canviar el valor. El javascript s'ha de ficar dins el jsp corresponent de webdbmodificable (activant amb  FilterForm.setAttachedAdditionalJspCode()

![imatge](https://user-images.githubusercontent.com/17084256/183581099-000451fc-6fc0-475d-9df4-46825bd1dc7b.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/183900213-46d50e07-be26-4e49-baac-33c4877d0ccf.png)
