### ISSUE TITLE
Descarregar el document arxivat

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#150]
Un cop acabat el issue #149

S'ha d'incloure un botó per cada petició, o bé al llistat de peticions o a la pantalla d'informació de la petició (o als dos llocs) per descarregar el document arxivat a través de la API d'Arxiu.

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/189909283-39457f09-0d98-40ec-8773-00f91f89badf.png)
