### ISSUE TITLE
Millores en Grups

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#154]
Millores en Grups:

(1) L'etiqueta Nom grup:
(1.a) "Nom grup" s'ha de canviar per "Nom"
(1.b) Ha de ser de tipus Input Text (no TextArea)

![imatge](https://user-images.githubusercontent.com/17084256/183637859-0ccf5375-d67e-47d8-919a-7bce151d0616.png)

(2) El camp  "Nom grup"  ha de ser Not Null
![imatge](https://user-images.githubusercontent.com/17084256/183638104-32ce096e-e2c4-4ecd-a19b-d3c4d4cb8e1b.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/183848343-16e0fe75-2552-40fe-87c9-b4f0ee0313c3.png)
