### ISSUE TITLE
Afegir Petició de Firma emprant Plantilles de Flux de Firmes del propi usuari

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#155]
Afegir Petició de Firma emprant Plantilles de Flux de Firmes del propi usuari. 
(1) Dinamicament amb JAVASCRIPT modificar algunes de les files de la taula (Per exemple NIF) per afegir una etiqueta Flux de Firmes) i en la columna dreta afegir una combobox amb el llistat de FluxDefirmes
(2) A l'hora de crear el flux per enviar a PortaFIb s'haurà de instanciar la Plantilla (convertirla a Flux de Firmes) per adjuntar-la a la petició

![imatge](https://user-images.githubusercontent.com/17084256/184083066-65241c8c-a2e9-48d3-a59e-2833729c1cc5.png)

![imatge](https://user-images.githubusercontent.com/17084256/184083468-0e3c1dce-8bfe-41bf-8b47-94b716c77d0c.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat: 
![image](https://user-images.githubusercontent.com/95921330/185589240-a3e14706-4163-4a60-ba9b-22079f83c11a.png)
