### ISSUE TITLE
Guardar fitxer signat rebut en el callback

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#16]
Depèn de "Fer firmar document per NIF destinatari #26"

Guardar fitxer signat rebut en al callback. Quan es rebi en el CallBack una notificació d'un event de tipus Peticio de Firma Finalitzada, llavors:
(1) Es consultarà a PortaFIb i es descarregarà la signatura (veure mètode comentat de la classe CallBack).
(2) Es creara el fitxer en BBDD i fisicament emprant FileSystemManager
(3) S'actualitzarà el camp fitxerFirmatID de Peticio de enviaFIB.

**Comment by fbosch-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/40387703/169512220-c461dcdd-4129-416b-be57-8a7ae67917a5.png)
