### ISSUE TITLE
Al pitjar reintentar Arxivat que surti una imatge tipus "loader"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#160]
Al pitjar el boto de Reintentar Arxivat que surti una imatge tipus "loader" per a que l'usuari no es cregui que l'odinador no fa res.
Provar amb un modal de Bootstrap: https://getbootstrap.com/docs/4.0/components/modal/
Revisar codi per si existeix alguna opció per deixar-ho allà fins que es carregui la pagia de nou (normalment els modals desapareixen al fer click)

**Comment by fbosch-fundaciobit** [comment]
Es mostra un spinner quan es reintenta l'arxivat:

![image](https://user-images.githubusercontent.com/40387703/185867002-8d2adb2f-fa62-4f70-945d-d024038e347d.png)
