### ISSUE TITLE
Ocultar Camps Avançats a l'usuari en la pantalla de petició

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#161]
(1) Moure Idioma del Document justa damunt de fitxer
(2) Afegir boto que sigui "Mostrar Camps Avançats" que mostri el camps encerclats en verd (Això s'ha de fer emprant javaScript)
(3) Afegir boto que sigui "Ocultar Camps Avançats"  que amagui  el camps encerclats en verd (Això s'ha de fer emprant javaScript)
NOTA: Només es mostrarà a la vegada un dels dos botons.
![imatge](https://user-images.githubusercontent.com/17084256/183894488-62256c01-c5b8-43d7-a4a6-d754f0ce4649.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/184352677-03e34167-8db3-454e-aa31-90578bd5eb05.png)
![image](https://user-images.githubusercontent.com/95921330/184352753-6185f22c-42a5-4e60-b0b7-1a9ab0c9361e.png)
