### ISSUE TITLE
Afegir CRON nocturn per esborrar Peticions de Firma de PortaFIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#162]
A causa de que s'han produït errors de BBDD despres d'haver esborrat la PEtició de PortaIFB, algunes peticions d'enviafib no han pogut finalitzar al haver desaperagut la seva Petició de PortaFIB. Actualment les peticion de PortaFIB NO s'esborren.

Fer un cron o timer nocturn (per exemple a les 4,5,i 6 de la dematinada  per esborrar les peticions de portafib.
Una proposta seria posar un prefix al codi de la petició portafib que sigui "ESBORRADA_". Totes les peticions que s'esborrin nocturnament actualitzaràn el seu portafirmesID.

NOTES:
    (1) Utilitzar SCHEDULE de jakartaEE: https://www.baeldung.com/scheduling-in-java-enterprise-edition
    (2) El filtre es farà sobre peticions firmades o finalitzades amb error i que el seu portafibID no contengui "ESBORRADA_"

**Comment by fbosch-fundaciobit** [comment]
S'ha implementat el CRON que s'executa diariament a les 4 del vespre:

![image](https://user-images.githubusercontent.com/40387703/187613325-9934ae76-0e39-4ace-949b-0d217cc9facb.png)
