### ISSUE TITLE
Revisar mètode PeticioLogicaEJB::reintentarGuardarFitxerArxiu()

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#163]
Revisar mètode PeticioLogicaEJB::reintentarGuardarFitxerArxiu() i intentar evitar l'us de FUTURE.
Consultar a @anadal-fundaciobit abans de començar aquest issue.

**Comment by fbosch-fundaciobit** [comment]
Els reintents d'arxivat ara es fan de forma sincrona i es poden veure els errors si falla el reintent al llistat:

![image](https://user-images.githubusercontent.com/40387703/185091080-bb12af7b-7a4d-4af9-9a82-40b174a0c21b.png)
