### ISSUE TITLE
Copiar opció de menu "Plantilles de Flux de Firmes" a Administrador

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#164]
Collir l'opció de menú "Llistat de Plantilles de Flux de Firmes " de usuari i moure-la a Administrador com a opció de menú titulada "Plantilles de Flux de Firmes de l'Entitat":
(1) S'haurà de modificar sessionfilterform
(2) S'haurà de crear nous tiles de tipus admin apuntant al mateix fitxer jsp
(3) La cerca i creació de plantilles enlloc d'usar {owner=LoginINfo.username} haurà d'utilitzar directament la cadena "enviafib". Amb {owner=enviafib} es coneixerà quines són d'Administrador

![imatge](https://user-images.githubusercontent.com/17084256/184084620-ab162b13-ea57-4c04-98ad-7801f6b883b9.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha afegit l'enllaç per veure les plantilles de flux de firma de l'usuari "enviafib".


![image](https://user-images.githubusercontent.com/40387703/187196986-f9e606c5-0713-474a-978c-2c1f6285908f.png)
