### ISSUE TITLE
Gestionar Plantilles Temporal que no s'han esborrat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#168]
En el servidor de PortaFIB s'utilitzen plantilles per la Creació d'una Firma personalitzada. Se li posa un flag a la descripció {temporal=true} i una data de creacio {creation=12343454312}.
S'ha de crear una opció de menu d'administrador titulada "Neteja de Plantilles de Flux Obsoletes" còpia de " Copiar opció de menu "Plantilles de Flux de Firmes" a Administrador #164 " on la cerca siguin {temporal=true} i creació sigui més antiga de fa dues hores. S'ha de mostrar un boto únicament per esborrar.

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/187694835-7f88c196-b1bc-4072-a169-61f38c10ccd5.png)
