### ISSUE TITLE
Fer que Plugin d'Arxiu  llegeixi properties i classe de BBDD enlloc de Propietats de sistema

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#169]
Fer que Plugin d'Arxiu llegeixi properties i classe de BBDD enlloc de Propietats de sistema

Es tracta de fer que la informació del PLugin d'Arxiu és guardi en la taula efi_plugin de BBDD.
Ja hi ha un exemple fet per EstructuraOrganitzativa( PluginEstructuraOrganitzativaLogicaEJB.java i PluginEstructuraOrganitzativaLogicaService.java)

Es tractaria d'adaptar la classe PluginArxiuLogicaEJB per a que enlloc d'obtenir les dades de Properties les obtengui de la taula de Plugin.

NOTA 1: S'haurà fe fer un nou tipus de PLugin (Veure Constants)
NOTA 2: PluginArxiuLogicaEJB  s'haurà d'estendre de AbstractPluginLogicaEJB i fer el corresponent pel Service.
NOTA 3: Comentar el mètode getInstancePluginArxiu() de PluginArxiuLogicaEJB i usar el de AbstractPluginLogicaEJB.

**Comment by ptrias-fundaciobit** [comment]
Solucionat!
