### ISSUE TITLE
Canviar el camp NOM de la taula Petició per un que entenguin millor els usuaris

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/enviafib#170]
Canviar el camp NOM de la taula Petició per un que entenguin millor els usuaris

**Comment by fbosch-fundaciobit** [comment]
Canviar "Nom" de la petició per "Titol".

El titol del llistat ha d'especificar que son "Peticions de Firma". En el titol ha de posar "Llistat de Peticions de Firma", així com al menú lateral.

**Comment by fbosch-fundaciobit** [comment]
S'han canviat els literals de la pantalla del llistat de peticions, i la columna "nom" s'ha renombrat com a "titol"

**Comment by anadal-fundaciobit** [comment]
La BBDD no s'ha de tocar !!!!!!  Per això podem tocar les els noms de les etiquetes !!!!!  Tornar enrere el canvi de BBDD.

**Comment by fbosch-fundaciobit** [comment]
He canviat el nom a BBDD per "Nom", i deixat el Label com "Titol".
