### ISSUE TITLE
Actualitzar versió de Plugin d'Arxiu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#172]
Actualitzar versió de Plugin d'Arxiu. Des de la DGMAD ens comenten que ja hi ha disponible la versió 2.0.23.

Actualitzar API i PLugins d'ARXIU.

Comprovar que:

(1) Els tipus documentals majors que 50

**Comment by fbosch-fundaciobit** [comment]
S'ha actualitzat la versió del plugin d'Arxiu, i s'han solventat els errors de compilació (i testejat):

![image](https://user-images.githubusercontent.com/40387703/186157281-8ee53ee9-6ad2-4f02-9e41-14d3d7d90d89.png)
