### ISSUE TITLE
Arreglar problema amb enviar peticions amb un flux de firma

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/enviafib#173]
Arreglar problema amb enviar peticions amb un flux de firma

![image](https://user-images.githubusercontent.com/95921330/185069896-1edc62f8-fe08-4765-861e-268cf731e247.png)

No se encuentra la página /portafib/public/flowtemplate/null/user/flux/callbackflux/R6xYaE8ZwrGKZnzO2m5llq5ELqMP

**Comment by fbosch-fundaciobit** [comment]
Aquest error s'ha corregit canviant "localhost" de la URL per el nom d'usuari.

S'ha trobat un altre error arxivant el document amb el Plugin d'Arxiu ja que no es guardaven bé les dades de la petició a BBDD que també s'ha corregit:

![image](https://user-images.githubusercontent.com/40387703/185116824-206e44d3-71e1-46d2-81ed-8a754ceaebc7.png)
