### ISSUE TITLE
Arreglar pantalla de Plugin d'Arxiu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#174]
(1) El títol surt malament: NOTA: Les comentes s'han d'escriure ´ i no '
(2) Llevar boto de prova

![imatge](https://user-images.githubusercontent.com/17084256/185072482-596bb3a1-1e6f-405d-a818-c2d6de23205c.png)

**Comment by fbosch-fundaciobit** [comment]
Corregits els titols, i eliminat el botó de provar plugin:

![image](https://user-images.githubusercontent.com/40387703/186105535-c9acffc9-5c22-4501-af7d-c0a3bf328788.png)
