### ISSUE TITLE
Missatges duplicats al crear una petició de firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#175]
Missatges duplicats al crear una petició de firma. Només n'ha de sortir un indicant que s'ha creat i enviat correctament.

(1) Cercar la linia on s'escriu el missatge "Peticio amb Id: 1001 enviada correctament."
(2) Justa abans afegir el codi  per esborrar tots els missatges de HTMLUtils
(3) Modificar els missatge  "Peticio amb Id: 1001 enviada correctament." per alguna cosa que indique que la petició s'ha creada i enviada correctament.

![imatge](https://user-images.githubusercontent.com/17084256/185077992-2f1912a5-51d4-42dc-8518-473829ffb9d2.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha afegit el missatge que indica que s'ha creat i enviat la petició, i s'ha afegit just abans la instrucció per eliminar els missatges previs, però el missatge segueix apareixent duplicat. S'ha de revisar, si el missatge de creació autogenerat es crida després d'aquestes comandes, s'haurà de cercar una solució alternativa.

**Comment by ptrias-fundaciobit** [comment]
Solucionat: 
![image](https://user-images.githubusercontent.com/95921330/187617718-80ddffc6-e4a0-4dc5-9a57-d78f79568efc.png)

https://github.com/Fundacio-Bit/enviafib/commit/e921c26146fc91293116b3db7fc58ffb49ab4cc0
