### ISSUE TITLE
Emprant Firma personalitzada no apareix la zona Drag&Drop

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#176]
Emprant Firma personalitzada no apareix la zona Drag&Drop

![imatge](https://user-images.githubusercontent.com/17084256/185084003-d8f963e5-c82d-427f-8373-aec3b4e525bc.png)

![imatge](https://user-images.githubusercontent.com/17084256/185084952-9da40f94-5559-4353-992b-a432892ccc56.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/187625020-c2d11086-bf4d-4fee-a479-c7c0727776d2.png)
