### ISSUE TITLE
Revisar entrades XYZ  i arreglar-les

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#177]
Pel codi hi ha entrades XYZ ZZZ o XYZ ZZZ TRA que indiquen trossos de codi que tenen alguna cosa pendent.
Revisar per tot el codi aquestes entrades i arrglar el que indiquin.

**Comment by ptrias-fundaciobit** [comment]
Arreglats molts dels errors. Nou codi per categories XYZs
XYZ ZZZ TMP -> Per mes envant s'ha de tornar a revisar
XYZ ZZZ TRA -> TODO que s'ha de fer
XYZ ZZZ TRAD -> S'ha afegir/arreglar una traducció
XYZ ZZZ TRA - ISSUE -> S'ha de fer un issue per aquest TODO
XYZ ZZZ TRA - [username] -> L'ha de resoldre l'usuari indicat
