### ISSUE TITLE
Llistat desconegut després de crear peticio

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#181]
Llistat desconegut després de crear petició. 
(1) Pot ser s'hauria d'anar al llistat de peticions pendents ???
(2) Aquest llistat hauria de desaparèixer????

Consultar-ho amb en @atrobat-dgtic 

![imatge](https://user-images.githubusercontent.com/17084256/188418461-5dba5d6b-7f69-431c-ae7b-9fb1f753c72a.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha solventat al commit:

https://github.com/Fundacio-Bit/enviafib/commit/bfa51cbeb02d10dc3fbe746d8b7a88197c7e5c93

Per l'issue: #182
