### ISSUE TITLE
Revisar dades inicials de PostgreSQL i Oracle

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#184]
Falten afegir dades inicials als scripts de DATA de postgres i oracle: seriesdocumentals, plugins d'arxiu, ...   

Revisar tots els scripts de update_data.

**Comment by fbosch-fundaciobit** [comment]
S'han afegit les comandes inicials de la versió 1.0.0 als scripts de dades generals:

![image](https://user-images.githubusercontent.com/40387703/188856525-5e1018c2-b9a9-46bb-a7a1-c6c08859c6a1.png)
