### ISSUE TITLE
Controlar errors en Authentication al donar d'alta un usuari

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#186]
Controlar errors en Authentication al donar d'alta un usuari.

Con reproduir: afegir un caràcter X al username de BBDD del usuari que empram. Després intentar loguejar i ens donarà un error.

Fer que quan no es pugui guardar l'usuari, (1) controlar l'error (2) enlloc d'anar a editar l'usuari, anar a creació d'usuari.

**Comment by fbosch-fundaciobit** [comment]
Ja es controlen els errors d'autenticació, i redirigeixen a la pàgina de creació d'usuari, on es pot crear un nou usuari:

![image](https://user-images.githubusercontent.com/40387703/193251403-13eb3fba-f37d-481b-8c6d-a77ecb2db99b.png)

![image](https://user-images.githubusercontent.com/40387703/193251419-5f5c885e-3772-456c-b199-4e3204cb61ec.png)
