### ISSUE TITLE
Posar titol com toca a cada tipus de Firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#188]
Falta arreglar.

Posar titol com toca a cada tipus de Firma

![imatge](https://user-images.githubusercontent.com/17084256/188870470-24e343e1-0bd8-430e-b6e2-2ea934010259.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat per a tots els tipus de peticions:
![image](https://user-images.githubusercontent.com/95921330/189106038-f5d869a2-7b9c-4f2a-b280-4f56949bd8d1.png)
