### ISSUE TITLE
Error en la Pantalla de Gestió de PLugins d'Arxiu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#190]
- El paths no poden estar en majuscules
- El menú no s'activa en negreta.

![imatge](https://user-images.githubusercontent.com/17084256/188884613-22034d37-180d-4c64-9040-cb1a1eda5aaa.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat: 
![image](https://user-images.githubusercontent.com/95921330/189082770-c4652802-3d07-458d-9166-61e36188e3fb.png)
