### ISSUE TITLE
Ignorar callback de petició de firma si la petició es troba en estat:, error_arxivant o error_tancant_expedient

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#191]
Si l'estat de la petició es de Error Arxivant, o Error Tancant Expedient, s'han d'ignorar les respostes del callback d'aquestes peticions.

**Comment by anadal-fundaciobit** [comment]
Si s'implementa només servirà per ocultar errors.
