### ISSUE TITLE
Llistat de Tipus Documental no ordenat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#194]
L'entrada " ----- Seleccioni un tipus documental ----- " no surt a dalt de tot.

Veure que està passant ...

![imatge](https://user-images.githubusercontent.com/17084256/189311017-8960a657-246e-4de5-bef6-3de226d8d359.png)

**Comment by fbosch-fundaciobit** [comment]
Els tipus documentals surten ordenats, amb l'opció de "Seleccioni un tipus documental" a dalt de tot:

![image](https://user-images.githubusercontent.com/40387703/189590163-2bc3924e-eb1f-427f-ac94-27d1758f01d8.png)
