### ISSUE TITLE
Ocultar la columna finalitzada a Peticions pendents

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#195]
Ocultar la columna finalitzada a Peticions pendents ja que no té sentit.
NOTA: Revisar que els altres llistats queden bé.

![imatge](https://user-images.githubusercontent.com/17084256/189312464-c5b1f611-f451-46ef-9861-337df6d449d8.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha amagat la columna de data de finalització a la pantalla de peticions pendents:

![image](https://user-images.githubusercontent.com/40387703/189831025-eb9659d1-ab95-4a87-9ee9-38af53a31336.png)
