### ISSUE TITLE
Pantalla Completa en Edició de l'usuari

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#196]
Pantalla Completa en Edició de l'usuari.

(1) S'ha de mostrar en la pipella Inici
(2) Revisar que l'edició d'usuai en pipella User surt bé
(2) Revisar que l'edició de l'usuari en un usuari nou va bé (aquest si ha de sortir a pantalla completa)

![imatge](https://user-images.githubusercontent.com/17084256/189850740-3d583fc7-b83e-420f-9a86-1be01631f607.png)

![imatge](https://user-images.githubusercontent.com/17084256/189850764-f12110eb-00bb-4ab9-8639-3bb09f327591.png)

**Comment by fbosch-fundaciobit** [comment]
Ja apareix la pantalla d'edició de usuari correctament a les pantalles corresponents:

![image](https://user-images.githubusercontent.com/40387703/190138194-7c09f0e6-879d-4578-b71b-0c9de69b52bc.png)
