### ISSUE TITLE
Falta Literal "plugin.desactivar"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#198]
Falta Literal "plugins.desactivar"

![imatge](https://user-images.githubusercontent.com/17084256/189886101-2618e10c-7836-4b9e-b281-ced1ebbe80a6.png)

**Comment by ptrias-fundaciobit** [comment]
Corregit
![image](https://user-images.githubusercontent.com/95921330/191956575-010f4e4a-90a9-4c9e-985c-bf9963ccab6e.png)
