### ISSUE TITLE
La pantalla d'informació d'enviafib no es mostra

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#199]
(1) La pantalla de "Informació" d'EnviaFIB, o sigui el HOME,  del menú de Usuari no es mostra bé (Veure Captura) 
(2) A més canviar "Informació" per alguna cosa com "About ..."
(3) En la pantalla d'inici, canviar "Pàgina Principal" per "About..." i moure-la al final

![image](https://user-images.githubusercontent.com/40387703/189891073-8f667ed3-759e-4cdc-b4e3-458f2275317d.png)

![image](https://user-images.githubusercontent.com/40387703/189891105-e3d49d16-38ad-4a8c-8e16-5cfce594a0bd.png)

**Comment by ptrias-fundaciobit** [comment]
1: Fet
![image](https://user-images.githubusercontent.com/95921330/190115226-e9ed8b24-fa02-4152-a226-aa5f23add1b9.png)

2: Fet
![image](https://user-images.githubusercontent.com/95921330/190115107-db7da021-4a42-4962-b6c2-1df8871addca.png)

3: Fet
![image](https://user-images.githubusercontent.com/95921330/190115018-d6ef7689-4f3b-4ea2-af4b-8b6fd2ddbb85.png)
