### ISSUE TITLE
Modificar URL del mail per descarregar el fitxer Firmat.

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/enviafib#201]
Modificar URL del mail per descarregar el fitxer Firmat.

Si està arxivat, enviar la URL de concsv amb csv. Sino, enviar-ho com ara

**Comment by fbosch-fundaciobit** [comment]
Ja s'envia el mail correctament. 

Amb el codi CSV, amb un enllaç public, i que descarrega el fitxer d'Arxiu.

![image](https://user-images.githubusercontent.com/40387703/192512713-0ae45434-a074-4fef-8a05-e332cdfc85c3.png)
