### ISSUE TITLE
Peticio firma personalitzada no es copia el Titol del Flux cap a Titol Peticio

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#202]
En les peticions de Firma personalitzada primer es demana el nom del flux (captura 1) i després arribam al punt de omplir les dades de la Petició. En aquesta s'hauria de copiar el nom del FLUX al TÍTOL.

![imatge](https://user-images.githubusercontent.com/17084256/189899568-eba5893c-8c82-4462-938b-45100485dc13.png)

![imatge](https://user-images.githubusercontent.com/17084256/189899742-eae04ead-60e4-4e66-92f9-6e11045df20a.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/191946874-0dbf910a-56fd-4964-a929-01d6ee85654a.png)
![image](https://user-images.githubusercontent.com/95921330/191946931-7a4c67b5-29af-4d40-9dba-d0d16ae99f17.png)
