### ISSUE TITLE
Missatges duplicats al crear AutoFirma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#203]
Quan es crea una AutoFirma apareixen dos missatges. Simplificar-ho en un. (Cercar codi Htmlutil.deleteMissatges() i copiar comportament.)

![imatge](https://user-images.githubusercontent.com/17084256/189901274-bf687b87-c494-4ac5-a809-c51b574c2972.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:

**Comment by anadal-fundaciobit** [comment]
Amb Firma "AutoFirma" no s'envia res. Crec que aquí el millor seria esborrar els missatges.

**Comment by ptrias-fundaciobit** [comment]
Solucionat
