### ISSUE TITLE
En estat ERROR ARXIVANT permetre esborrar una petició.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#204]
En estat ERROR ARXIVANT permetre esborrar una petició.

![imatge](https://user-images.githubusercontent.com/17084256/190073722-8bc4b8cd-8224-4b01-a6eb-469284f04d39.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:; 
![image](https://user-images.githubusercontent.com/95921330/190103124-273a3f4b-4fd1-47e7-a615-f5f86c40da6f.png)
