### ISSUE TITLE
Respondre OK a callback de peticions no existents.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#206]
Quan es rep una notificació d'una petició que no tenim registrada s'ha de contestar a PortaFIB amb un OK. Lo contrari, que es lo que passa ara, estirà reintentat la notificació i a més quedarà a la llista de Notificacions de PortaFIB.

![imatge](https://user-images.githubusercontent.com/17084256/190078070-8f245aee-9df6-40e5-9607-c85bc3d0e98c.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat
