### ISSUE TITLE
Es poden esborrar peticions finalitzades des de "Eliminar Seleccionats"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#208]
Es poden esborrar peticions finalitzades des de "Eliminar Seleccionats"

![imatge](https://user-images.githubusercontent.com/17084256/190118106-4d5a801c-f190-4a3a-9c10-b1583abaf494.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/192232603-e44b77bf-d2f3-4cde-9962-2c06d8235091.png)
