### ISSUE TITLE
Canvi en Títols de Peticions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#209]
Del menú d'usuari canviar el menú "Peticions pendents de firma" per "Peticions pendents" i a més fer que el títol del llistat sigui el mateix del menú

![imatge](https://user-images.githubusercontent.com/17084256/190119997-4067b6f1-f458-4a12-993d-e6ebe39cfd3a.png)

**Comment by ptrias-fundaciobit** [comment]
Fet:
![image](https://user-images.githubusercontent.com/95921330/192513105-732b4e4b-d033-4c07-a8a9-1eb6e56939dc.png)
