### ISSUE TITLE
Implementar funció per veure fitxer firmat

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/enviafib#21]
Depen de "Fer firmar document per NIF destinatari #26"
A les peticions que tenguin el fitxer firmat, afegir un botó per descarregar el fitxer

**Comment by ptrias-fundaciobit** [comment]
Solucionat
![image](https://user-images.githubusercontent.com/95921330/169285190-15ccc2fb-30d1-408e-8f26-cba952ac8c25.png)
![image](https://user-images.githubusercontent.com/95921330/169285733-3536a307-263e-40b7-b63c-04250d17942f.png)

**Comment by anadal-fundaciobit** [comment]
Dues coses:
(1) El missatges de Log han de ser el més concrets possibles per quan es ratregi algun bug. El missatge de la captura següent no ens aporta RES. Afegir com a mínim el ID de petició de POrtaFIB i tipus d'event ...
![imagen](https://user-images.githubusercontent.com/17084256/169463691-5e834c6b-931e-44c7-a964-4d4244df91be.png)

(2) Tots els missatges que s'enviin a l'usuari web han de ser traduibles (I18NUtils.tradueix ("codi")). En el cas de rebre una I18NException, d'aquesta no podem mostrar el getMessage(), l'hem de traduir directament i mostrar: I18NUtils.getTraduccio?(e)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:

**Comment by ptrias-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/95921330/169529080-264f05ce-62aa-4119-9295-d416a3f667e3.png)
![image](https://user-images.githubusercontent.com/95921330/169529131-793f02e7-d0be-4c4d-9d36-60047abb4958.png)

**Comment by ptrias-fundaciobit** [comment]
Solucioat: 
![image](https://user-images.githubusercontent.com/95921330/169534960-786803bd-3501-4e61-91c7-5b4460eb6f2d.png)
![image](https://user-images.githubusercontent.com/95921330/169535145-62a6c1d6-09a2-40d6-b278-b8502c8b6728.png)

**Comment by anadal-fundaciobit** [comment]
Un parell de coses:


(1) Al fitxer "enviafib-back/src/main/resources/missatges_en.properties" li has canviat la codificació

![imagen](https://user-images.githubusercontent.com/17084256/169752428-d4d8a583-30d4-4026-9e66-3274af174a1f.png)


(2) Aquest errors 
callback.event.rebuig.error=S'ha rebut un event de REBUIG, pero no s'ha trobat la peticio d'enviafib.
callback.event.firma.error=S'ha rebut un event de FIRMA, pero no s'ha trobat la peticio que l'hi correspon a enviafib.
callback.event.enproces.error=S'ha rebut un event de EN PROCES, pero no s'ha trobat la peticio que l'hi correspon a enviafib.

s'han de convertir en un de sol

callback.event.error=S'ha rebut un event amb ID {0} de tipus {1} ({2}) amb Id de petició de firma {3} pero no s'ha trobat la peticiÓ<= d'enviafib associada.

(3) Els LOGs no s'han de traduir, només allò que es mostra a l'usuari

![imagen](https://user-images.githubusercontent.com/17084256/169752558-3f73714f-22a9-4ab3-9b99-3754080cda88.png)

![imagen](https://user-images.githubusercontent.com/17084256/169752678-fc96010f-ba34-4ead-a4f9-d1fc8f672516.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionats punts 2 i 3, amb la eliminació de la funció de descarregar fitxer no ha estat necessari fer molts de canvis. La codificació del fitxer de missatges no l'he sabut arreglar

**Comment by ptrias-fundaciobit** [comment]
Solucionat
