### ISSUE TITLE
Fer que els fitxers de traduccions no es copiin de EJB a BACK

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#211]
Els fitxers, de traduccions que es troben a capa EJB es copien a BACK. Es copien al directori de codi font de BACK cosa que moltes de vegades duu a cometre errors als desenvolupadors de quin lloc ficar certa traducció.
Cercar algun altra sistema per incloure aquests fitxers al war de back: per exemple veure si es poden copiar a "enviafib-back\target\classes" però s'ha de triar la fase de maven correctament.

Un cop funcioni, comentar la solució a @anadal-fundaciobit  i mirar de migrar-la a GENAPP.

![imatge](https://user-images.githubusercontent.com/17084256/190347319-da10b1b9-c4a4-432f-9ae1-94ef4dd9c1fd.png)

![imatge](https://user-images.githubusercontent.com/17084256/190347469-266a2ee6-756b-46b6-8664-b737ee424a04.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/190622029-8cfad7e9-68d9-48d2-abbf-88e06dd7a4fe.png)
![image](https://user-images.githubusercontent.com/95921330/190622069-ba87a685-afb4-4c09-ae88-f0710511e4aa.png)

**Comment by anadal-fundaciobit** [comment]
Pareix que s'ha canviat el directori destí per ${project.basedir}/target.  
Pareix ser que hi ha gent que canvia de nom el directori "target" per la qual cosa seria millor utilitzar la propietat "${project.build.directory}"

**${project.build.directory} is equivalent to ${project.basedir}/target**

**Comment by ptrias-fundaciobit** [comment]
Solucionat:
![image](https://user-images.githubusercontent.com/95921330/191202421-5ab14ee8-6b2b-441d-bc39-625f5fbaf893.png)

**Comment by anadal-fundaciobit** [comment]
has d'esborrar això ja que no s'utilitza ...

![imatge](https://user-images.githubusercontent.com/17084256/191430677-35fcc910-dd7c-4a30-b72a-45342f7aadff.png)

**Comment by anadal-fundaciobit** [comment]
A més s'han d'esborrar els fitxers de .gitignore.

**Comment by ptrias-fundaciobit** [comment]
Fet
