### ISSUE TITLE
Falta Traduccio

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#213]
![imatge](https://user-images.githubusercontent.com/17084256/190624978-cf158a45-9c62-452d-a55e-896679ec9c1a.png)

**Comment by ptrias-fundaciobit** [comment]
Fet
![image](https://user-images.githubusercontent.com/95921330/191490538-1c2f6c69-ac5f-4669-9c88-97e5483d88e2.png)
