### ISSUE TITLE
Si Plugin Estructura Organitzativa retorna null, llavors no cridar a UserInformation

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#214]
Quan per exemple cridam a secretari i aquest vall null, llavors no cridar al plugin de UserInformation que és una tonteria.

Fer que quan Plugin organitzatiba torni un null, llançar ja un error.

![imatge](https://user-images.githubusercontent.com/17084256/190961807-a27a3917-4d02-49e9-9897-20fd231f7df9.png)

**Comment by fbosch-fundaciobit** [comment]
Si s'intenta enviar una petició a un carrec que no té usuari assignat, apareix aquest missatge d'error:

![image](https://user-images.githubusercontent.com/40387703/192720643-17b3c362-de84-4c6e-94ff-b578cdcb7778.png)
