### ISSUE TITLE
Ocultar NIF  en les firmes de Tipus Càrrec i mostrar Nom.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#215]
En les firmes de Tipus Càrrec, és a dir, en les firmes que s'usa el Plugin d'Estructura Organitzativa, es mostra el NIF de per exemple el Gerent o Secretari. Fer que es mostri , per exemple en el subtitol, el nom de la persona que ocupa el càrrec i s'amagui el camp de NIF.

![imatge](https://user-images.githubusercontent.com/17084256/190962973-408f5a9f-5a18-4206-a826-3c2bfdbc5627.png)

**Comment by ptrias-fundaciobit** [comment]
Aarreglat:
![image](https://user-images.githubusercontent.com/95921330/192271064-2f611570-d03f-4e87-b4c5-3f0cab73f476.png)
