### ISSUE TITLE
Posar el títol del "menú" al títol del tipus de Firma.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#216]
Posar el títol del "menú" al títol del tipus de Firma.

En el mètode SHOW de MenuUserController afegir una variable de sessió que contengui el nom del menú o millor el codi.

EN la classe Abstract de Tipus de Firma fer que es mostri com a títol el que hi hagi dins de la variable de sessió.

 

![imatge](https://user-images.githubusercontent.com/17084256/190963594-e75d2e45-c458-4894-a657-4a3a1a79a316.png)

**Comment by ptrias-fundaciobit** [comment]
Fet: 
![image](https://user-images.githubusercontent.com/95921330/192512917-bc9864ff-d192-47c1-bf90-ff638ae88630.png)
![image](https://user-images.githubusercontent.com/95921330/192513039-14bd17d1-a55b-40bc-a2ac-7b60000801a0.png)
