### ISSUE TITLE
Al final d'Autofirma acabar al llistat de Finalitzades o Rebutjades

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#221]
Al final d'Autofirma, sabem si la cosa ha anat bé o no, d'aquí que enlloc de redirigir a la llista de pendents millor acabar al llistat de Finalitzades o Rebutjades segons com hagi acabat la petició.

**Comment by ptrias-fundaciobit** [comment]
Solucionat: Quan va bé s'envà a firmades, i quan va malament va a rebutjades

**Comment by ptrias-fundaciobit** [comment]
Falta commit

**Comment by ptrias-fundaciobit** [comment]
Fet
