### ISSUE TITLE
Actualitzar comandes sql de update per cridades GenQL

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#224]
En els mètodes eliminarPeticionsPortaFIB() i eliminarFitxersSignatsDeLocal() de la classe PeticioLogicaEJB hi ha cridades a update emprant sentències HQL. Un exemple és aquesta:

![imatge](https://user-images.githubusercontent.com/17084256/191692224-399e9a53-9cbc-4e66-8df2-71ad7d822c2b.png)

Ara des de GenQL es pot actualitzar 1,2, ... camps sense haver de crear la cridada HQL, sinó emprant comandes GenQL. L'exemple anterior en GenQL quedaria com:

`this.update(PeticioFields.FITXERFIRMATID, null, PeticioFields.FITXERFIRMATID.equal(fitxerFirmatID));`

Cercar si hi ha altres parts del codi amb updates HQL.

**Comment by ptrias-fundaciobit** [comment]
Solucionat
![image](https://user-images.githubusercontent.com/95921330/194028267-32db5eee-dc23-4d18-8c63-303af953055e.png)
![image](https://user-images.githubusercontent.com/95921330/194028338-6d89b12f-a6cc-4eee-97f4-d3bcd6bbdde6.png)
