### ISSUE TITLE
Falta traducció

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#227]
Falta traducció de success.desactivarplugin

![imatge](https://user-images.githubusercontent.com/17084256/192964321-fab86ab7-c69d-497d-9ab0-af81ee7dd1ee.png)

**Comment by fbosch-fundaciobit** [comment]
S'han creat les traduccions per l'activació i desactivació dels plugins:

![image](https://user-images.githubusercontent.com/40387703/193794610-b69b3ffe-55ef-4e2a-8e70-97906c3a3a24.png)
