### ISSUE TITLE
Revisar quan les peticions de firma no troben usuari al PortaFIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#233]
Revisar quan les peticions de firma (de tots els tipus excepte els de Flux) no troben usuari al PortaFIB.

Pareix que no es fa cas dels errors durant la creació de la Petició de Firma de PortaFIB i sempre se li diu a l'usuari que la cosa ha anat bé (veure captura)

Com reproduir:
    Enviar a firmar a un NIF que no estigui a la BBDD de PortaFIB.

![imatge](https://user-images.githubusercontent.com/17084256/193234705-02e1031a-8c1c-45e6-8658-598af6afb4bd.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat. Ara quan nomes anira a llistat de pendents quan hagi anat tot be, sino, al llistat de rebuitgats
