### ISSUE TITLE
Substituir  genapp.comodi per traduccions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#234]
(1) El genapp.comodi només s'ha de fer servir per temes de desenvolupament. Substituir "genapp.comodi" per traduccions del fitxer de missatges.

(2) A més, estructures del tipus:

```
 String carrecName = I18NUtils.tradueix(carrec);
 String msg = I18NUtils.tradueix("error.plugin.estructuraorganitzativa.carrecnotrobat", carrecName);
throw new I18NException("genapp.comodi", msg, carrecName);
```

s'ha de substituir per:

```
String carrecName = I18NUtils.tradueix(carrec);
 throw new I18NException("error.plugin.estructuraorganitzativa.carrecnotrobat", new I18NArgumentString(carrecName));
```

**Comment by fbosch-fundaciobit** [comment]
S'han substityuit les estructures amb genapp.comodi per estructures amb els missatges de traducció directament.
