### ISSUE TITLE
Que fer quan no es pot obtenir el codi Dir3 ...

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#235]
Que fer quan no es pot obtenir el codi Dir3 ...

Actualment la solució passa per cridar a obtenir dir3 del departament i si no el de l'arrea i sinó al de l'entitat.

Falta controlar que si Dir3 de l'entitat també val NULL que redirigeixi a la pàgina d'error (#210) indicant a l'usuari que contacti amb l'Administrador per a que configuri correctament el DIR3 del Plugin d'Estructura Organitzativa.

![imatge](https://user-images.githubusercontent.com/17084256/193241430-9ecb2079-4156-407c-a9bc-2840413f8371.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha complett l'error, i ara es mostra a la pantalla d'error creada a l'issue #210 :

![image](https://user-images.githubusercontent.com/40387703/195557088-7142e295-5366-4bc8-9bfb-0b1b70397483.png)

**Comment by anadal-fundaciobit** [comment]
No ha de sortir tant d'error !!!!! Simplicifar el missatge .

**Comment by fbosch-fundaciobit** [comment]
S'ha simplificat el missatge: 

![image](https://user-images.githubusercontent.com/40387703/195576367-b57ac16f-c531-423b-9c87-986c902c2e46.png)
