### ISSUE TITLE
Reubicar botons de mostrar camps avançats.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#237]
Ve de l'issue " Ocultar Camps Avançats a l'usuari en la pantalla de petició #161 ".

Els botons que es varen definir en aquest issue s'han de defiir com additionalbutton i no directament des de javascript com estan ara. Si s'observa en les captures, els botons han d'estar a la dreta del títol i en el cas d'ocultar camps estan davall ocupant espai innecessari.

![imatge](https://user-images.githubusercontent.com/17084256/195015886-478a1cab-305d-4e0f-819b-78382d8c64c4.png)

![imatge](https://user-images.githubusercontent.com/17084256/195015903-e38eb13d-660a-4959-84fc-5368a160bab9.png)

**Comment by ptrias-fundaciobit** [comment]
addAdditionalbutton a llistats es posa adalt, on demana l'issue, pero a formularis es crea abaix. El mateix codi a form i a filterform fa aixó:
![image](https://user-images.githubusercontent.com/95921330/195589907-8a0faadd-a75e-46be-918c-3c62cb3148fb.png)
![image](https://user-images.githubusercontent.com/95921330/195589965-3d596ba9-3562-4242-bc61-a22194aad70b.png)

Està fet així per poder tenir el botó adalt

**Comment by anadal-fundaciobit** [comment]
Val. Doncs ho canviarem per dos botons abaix de color warning. Et pareix?

**Comment by anadal-fundaciobit** [comment]
![imatge](https://user-images.githubusercontent.com/17084256/196926809-bd49ea31-91db-4182-88de-5b682f2d1c0d.png)
