### ISSUE TITLE
No es pot comparar una llista amb un String en JSTL

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#243]
En menu.jsp s'esta comparant una llista amb un String. S'ha de fer amb mètodes JSTL per exemple:

hasRole(ConstantsXXX.RoleUSER) && !hasRoles(ConstantsXXX.RoleAdmin)

Nota_1: Cercar hasRole com es realment
Nota_2: ConstantsXXX s'ha de crear emprant la llibreria unstandard sobre la classe de Constans de common

![imatge](https://user-images.githubusercontent.com/17084256/197121387-1e2f14f3-d43f-4c68-88e0-6094d0bed503.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha canviat el codi per fer servir la funció "hasRole" amb les constants d'Enviafib:

![image](https://user-images.githubusercontent.com/40387703/199440597-97c837c4-b740-47a3-9052-d35fe832617b.png)
