### ISSUE TITLE
Donar més espai i canvi de lletra en els llistat de peticions.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#247]
(1) EN GENERAL: Donar més espai i canvi de lletra en els llistat de peticions. Afegir qualsevol estil nou a la taula per fer-la més moderna.

(2) LLISTAT DE FIRMADES: No mostrar la columna Creada

![imatge](https://user-images.githubusercontent.com/17084256/198574892-5aae8c5e-9afd-4e8d-aa95-74202cece80d.png)

**Comment by ptrias-fundaciobit** [comment]
Corregit:
![image](https://user-images.githubusercontent.com/95921330/203765144-d2c9a640-0167-4825-8be2-3ea67227eb87.png)
