### ISSUE TITLE
En els tres llistats de peticions utilitzar botons enlloc de boto desplegable

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#249]
El llistat de peticions firmades utilitza la botonera desplegable en les accions enlloc d'una llista de botons. Fer que utilitzi una llista de botons. Veure mètode  setActionRender()????.

![imatge](https://user-images.githubusercontent.com/17084256/198576746-35bb22dc-460a-4f0c-a16c-b29fba06700d.png)

**Comment by fbosch-fundaciobit** [comment]
S'ha eliminat el desplegable d'accions, i ara es pinten els botons directament:

![image](https://user-images.githubusercontent.com/40387703/199449593-989f9ff4-2f2a-4157-935e-9d07f1353dc1.png)
