### ISSUE TITLE
Error en missatge quan falta fitxer

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#253]
Missatge molt estrany al no seleccionar fitxer en Firma per NIF ...

(1) Crec que "Erros" i "amb" no es correcte, a més el finals del missatge es incomprensible.
(2) La resta d'errors tampoc apareixen (per exemple no s'havia definit tipus documental que es obligatori i sortia sense error)

![imatge](https://user-images.githubusercontent.com/17084256/201289611-2644baf5-de17-43e2-af92-a48edc3caac1.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat: 
![image](https://user-images.githubusercontent.com/95921330/201343740-b02823c8-77bb-4018-ac13-eb37b020f983.png)
