### ISSUE TITLE
Fer firmar document per NIF destinatari

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#26]
Fer firmar document per NIF destinatari

- [x]  #7 
- [x] #8
- [x] #11
- [x] #15 
- [x] #13
- [x] #14
- [x] #12
- [x] #20 
- [x] #21 
- [x] #16 
- [x] #17
- [x] #27
- [x] #42

**Comment by fbosch-fundaciobit** [comment]
Es tanca l'issue per tancament de versió.
