### ISSUE TITLE
Eliminar de "Peticions Rebutjades" el filtres per error i excepció

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#260]
Eliminar de "Peticions Rebutjades" el filtres per error i excepció.

![imatge](https://user-images.githubusercontent.com/17084256/201603690-04ab0056-f4f3-419d-a62a-5c6da08e087e.png)

**Comment by anadal-fundaciobit** [comment]
Això ja s'ha fet.

**Comment by ptrias-fundaciobit** [comment]
Corregit.
1.Disseny del formulari
2. Filtres corregits
![image](https://user-images.githubusercontent.com/95921330/203765469-c862c868-ef6f-42bc-adfa-389b667684e7.png)
