### ISSUE TITLE
Fer capçalera més ample i nom amb font més gran.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#261]
Fer capçalera més ample i al nom d'usuari posar-li una mida de font més gran.

![imatge](https://user-images.githubusercontent.com/17084256/201604046-5eed0e65-2b98-4bc5-b6bd-41ef8d2ec2fc.png)

**Comment by ptrias-fundaciobit** [comment]
Corregit
![image](https://user-images.githubusercontent.com/95921330/203765602-4c7d2777-d331-404c-b24c-4a0a7f541dca.png)
![image](https://user-images.githubusercontent.com/95921330/203765695-9aa4ce4d-ed0f-4055-bad3-df9bfad01794.png)
