### ISSUE TITLE
Al logo llevar-li l'escut del govern i fer-ho similar als logos de les aplicacions CAIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#262]
Al logo:

![imatge](https://user-images.githubusercontent.com/17084256/201605317-c7e5a6f0-f3d2-4620-87cf-b967be3487f3.png)

(1) Llevar-li l'escut del govern
(2) Adaptar-ho als logos de les Aplicacions de CAIB. Veure https://www.caib.es/sites/programarilliure/ca/cataleg-27737/

**Comment by anadal-fundaciobit** [comment]
S'ha elegit un  un altre logo

**Comment by ptrias-fundaciobit** [comment]
Millorat!
![image](https://user-images.githubusercontent.com/95921330/203764839-9b7cd5fa-6627-4006-a220-b226e7e08be8.png)
