### ISSUE TITLE
Esborrar petició de firma del PortaFIB un cop rebuda la notificació de Firmada o Rebutjada

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#27]
Depen de "Fer firmar document per NIF destinatari #26"

Esborrar petició de firma del PortaFIB un cop rebuda la notificació de Firmada o Rebutjada.

**Comment by ptrias-fundaciobit** [comment]
Solucionat. S'ha implementat el mètode esborrarPeticioPortafib() que crida deleteSignatureRequest() de la api de portafib.
