### ISSUE TITLE
Envia notificació per correu quan una petició finalitzi

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#31]
S'ha d'enviar una notificació per correu quan una petició finalitzi, tant si es correctament com per rebuig.

(1) Afegir servei de correu a standalone (veure PortaFIB 2.2), als scripts afegir codi de configuració de correu
(2) La classe per enviar correu és la següent: enviafib-ejb/src/main/java/es/caib/enviafib/logic/utils/EmailUtil.java
(3) Preparar missatges d'enviament (firmat i rebuig), i validar-los amb @anadal-fundaciobit 
(4) Afegir codi en el CallBack per enviar correu
(5) Analitzar que fer en cas d'error d'enviament de correu: no fer res, aturar-ho tot, reintents,. ...

**Comment by ptrias-fundaciobit** [comment]
Solucionat. Falta definir format del correu, pero es farà a un altre issue
