### ISSUE TITLE
Preparar la BBDD per suportar enviament a Plugin d'Arxiu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#32]
S'ha de revisar DigitalIB i veure els camps necessaris per poder omplir les dades requerides per l'enviament a Arxiu (Revisar scripts de BBDD com Tipus Java dels POJOs)

(1) Afegir dins Petició
- java.lang.String arxiuFuncionariUsername;
- java.lang.String arxiuParamFuncionariNom;
- java.lang.String arxiuParamFuncionariNif;
- java.lang.String arxiuParamFuncionariDir3;
- java.lang.String arxiuReqParamDocEstatElabora;
- java.lang.Integer arxiuReqParamOrigen;
- java.lang.String arxiuReqParamInteressats;
- java.lang.String arxiuReqParamCiutadaNif;
- java.lang.String arxiuReqParamCiutadaNom;
- java.lang.String arxiuReqParamOrgans;
- java.lang.String arxiuOptParamProcedimentCodi;
- java.lang.String arxiuOptParamProcedimentNom;
- java.lang.String arxiuOptParamSerieDocumental;
- java.lang.String arxiuOptParamExpedientId;

**Comment by fbosch-fundaciobit** [comment]
Afegides les columnes necessaries per a l'enviament a Arxiu (basat en DigitalIB).

![image](https://user-images.githubusercontent.com/40387703/179720346-72b6c5d5-07b1-4a1f-9f2f-10bd3a30c490.png)
