### ISSUE TITLE
Gestió del Plugin d'Arxiu (EJB i BACK)

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#35]
(1) Copiar la gestió del Plugin d'Arxiu de digitaIB (https://github.com/GovernIB/digitalib/blob/digitalib-1.0/logic/src/main/java/es/caib/digitalib/logic/PluginArxiuLogicaEJB.java).

S'han d'adaptar els packages, dependències maven (de logic i de ear), dependències d'altres classes, .... 

(2) També s'haurà de clonar la gestió de BACK: https://github.com/GovernIB/digitalib/blob/digitalib-1.0/back/src/main/java/es/caib/digitalib/back/controller/admin/ArxiuPluginAdminController.java

S'han d'adaptar els packages, dependències d'altres classes, ....

**Comment by fbosch-fundaciobit** [comment]
Queda pendent:

- Canviar TextAreas per Text, els JavaName i els Labels (mirar com estan a DigitalIB) de les noves variables de Peticio i InfoArxiu.
- Llevar InfoArxiuID de la informació que es mostra a la llista de peticions.

**Comment by fbosch-fundaciobit** [comment]
Afegides dades i lògica necessaris per connectar amb la API d'arxiu i emmagatzemar-hi les peticions:

![image](https://user-images.githubusercontent.com/40387703/182834563-722a3d01-04bd-4d41-9ca1-daf0f6684738.png)
