### ISSUE TITLE
Apareix l'error "El camp NIF no té el format correcte" quan s'intenta enviar una petició mitjançant una plantilla de flux de firma de l'usuari

### ISSUE THREAD

**Issue by acuevas-dgtic** [Fundacio-Bit/enviafib#395]
Una vegada creat un flux de firma d'usuari, quan intentes enviar una petició des de l'acció "Enviar a firmar amb una plantilla de flux de firma de l'usuari", apareix l'error: "El camp NIF no té el format correcte", tant si es pitja el botó "Mostrar camps avançats" com si no. El camp "NIF d'interessats" està buit.

**Comment by acuevas-dgtic** [comment]
![~3769435](https://github.com/GovernIB/enviafib/assets/58417501/36d17704-4cea-47df-90b9-603784873448)

**Comment by ptrias-fundaciobit** [comment]
Resolt a l'issue #383
