### ISSUE TITLE
Moure Lògica de itext i gson a cap ejb

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#398]
Dins les dependències de la cap de Back hi ha itextpdf-5.4.3.jar i gson-2.8.2.redhat-5.jar.
La lògica que estigui associada a aquestes dues dependències s'ha de moure a la capa d'ejb i així com les dues dependències.

**Comment by ptrias-fundaciobit** [comment]
Fet
