### ISSUE TITLE
Prepara BBDD per guardar informació retornada de la cridada a Arxiu

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#40]
Dins DigitalIB hi ha una classe que gestiona la informació retornada de la cridada a Arxivat: https://github.com/GovernIB/digitalib/blob/digitalib-1.0/model/src/main/java/es/caib/digitalib/model/entity/InfoCustody.java

(1) Crear una taula a BBDD per guardar aquestes dades
(2) En aquesta nova taula hi ha d'haver una referència a la Petició.

NOTA: La taula SQL tabé es troba a DIGITALIB !!!!

**Comment by fbosch-fundaciobit** [comment]
S'ha afegit la taula efi_infocustody. Faltarà revisar algunes etiquetes si aquesta informació ha de ser visible als usuaris. Però es deixa per ara com a millora pendent:

![image](https://user-images.githubusercontent.com/40387703/179484753-ddc1fc6d-35ea-467c-8703-280e62d82dd1.png)
