### ISSUE TITLE
Menú de "Enviar document a signar" no funciona des d'Administrador i falta afegir accés a llistat de peticions des del menú anterior

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#406]
(1) Menú de "Enviar document a signar"  afegir opció per anar a llistat de peticions
(2) Menú de "Enviar document a signar" no funciona des d'Administrador

![imatge](https://github.com/user-attachments/assets/7b1d8f04-4f41-4dd9-92a3-117200347085)

**Comment by ptrias-fundaciobit** [comment]
Fet
