### ISSUE TITLE
Error de visualització al peu 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#407]
![imatge](https://github.com/user-attachments/assets/dd4de1cb-a875-44de-a5e5-940157f3e660)

**Comment by ptrias-fundaciobit** [comment]
https://www.youtube.com/watch?v=PSD5pFi6bx4

**Comment by ptrias-fundaciobit** [comment]
![image](https://github.com/user-attachments/assets/712e2165-c79a-4d35-a3cc-e078511ee9b1)
