### ISSUE TITLE
Afegir Servidor de EnviaFIB a OTAeWebApps

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#42]
Afegir Servidor de EnviaFIB a OTAeWebApps. A la màquina otaewebapps hi ha una APP de instanciagenerica. S'hi ha d'afegir-hi un servei de EnviaFIB.

En @ptrias-fundaciobit ha vist la instal·lació de InstanciaGenerica dins de otaewebapps, o sigui que en @ptrias-fundaciobit  mostri a en @fbosch-fundaciobit .

Aquesta ha de ser la darrera tasca d'aquest project.

**Comment by ptrias-fundaciobit** [comment]
Fet:
![image](https://user-images.githubusercontent.com/95921330/171600669-1da3c0b2-ca67-4f48-bf9a-d6e4a8f9f430.png)
