### ISSUE TITLE
Moure l'API de CallBack a apiinterna/public/portafibcallback

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#44]
Moure l'API de CallBack a apiinterna/public/portafibcallback. Fer una còpia de l'estructura d'API Interna de Carpeta (https://github.com/GovernIB/carpeta/tree/carpeta-1.1/carpeta-api-interna) adaptant nom, packages i implementacions.
Després moure el codi de CallBack al package es.caib.carpeta.apiinterna?.public.portafibcallback

Hi ha l'exemple de carpeta API:
(1) S'ha de fer una còpia del directori [carpeta-api-interna](https://github.com/GovernIB/carpeta/tree/carpeta-1.1/carpeta-api-interna) de carpeta a enviafib
(2) Canviar packages (java i al pom). Al pom s'ha de llevar la generació del client.
(3) Comentar codi especific de Carpeta 
(4) Revisar el pom.xml  de l'ear de carpeta per incloure el nou war.

(5) Copiar callback que hi ha al back dins un nou package:  es.caib.enviafib.apiinterna.public.portafibcallback

**Comment by ptrias-fundaciobit** [comment]
Solucionat
