### ISSUE TITLE
Enviar per email un document firmat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#45]
Poder enviar per email un document firmat. Afegir una altra opció al llistat de Peticions de EnviaFIB per poder enviar un document o l'enllaç al document d'Arxiu a una correu electronic.

**Comment by fbosch-fundaciobit** [comment]
Amb el nou botó d'enviar email, es pot enviar el document signat a un email introduit a la pantalla emergent. S'envia un email a la direcció introduida, amb un link al fitxer firmat:

![image](https://user-images.githubusercontent.com/40387703/173585768-a1958703-6669-4d08-a915-3da64011147f.png)
