### ISSUE TITLE
Conèixer de qui està pendent una Peticio de Firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#51]
Mirar si hi ha algun sistema per conèixer de qui està pendent una peticio de Firma.
En principi no hi ha cap sistema directe.
Si no es troba cap sistema directe, es podria cercar alguna forma com per exemple mostrar el flux de firmes per a que vegi de qui està pendent.

**Comment by fbosch-fundaciobit** [comment]
Ja existeix una opció per veure l'estat del flux:

![image](https://user-images.githubusercontent.com/40387703/202399031-e553f218-ef0a-4b0c-a9aa-4ed7bfebe7ae.png)
