### ISSUE TITLE
Canviar propietats d'accés a PortaFIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#67]
Le spropietats es.caib.enviafib.portafibgatewayv2, es.caib.enviafib.portafibusername i es.caib.enviafib.portafibpassword s'haurien de canviar per  es.caib.enviafib.portafib.apifirmaasync.url, es.caib.enviafib.portafib.apifirmaasync.username i es.caib.enviafib.portafib.apifirmaasync.password

![imagen](https://user-images.githubusercontent.com/17084256/173339089-4927223b-d118-43f1-9ccf-9cdba06077a1.png)

**Comment by fbosch-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/40387703/173823478-15ffb245-6597-4691-aa16-c7c341c28eec.png)
