### ISSUE TITLE
Primera entrada d'un usuari: Username no està readonly i falta NIF

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#68]
Quan un usuari entra per primera vegada a EnviaFIB el username hauria d'estar d'estar en readonly. A més per alguna raó no s'obté el  NIF. 

![imagen](https://user-images.githubusercontent.com/17084256/173340353-61f3f211-7daf-4f62-b173-2791e60709c1.png)

**Comment by fbosch-fundaciobit** [comment]
Els camps "username" i "nif" de la finestra d'edició d'usuari s'han definit com a "readonly" si ja contenen un valor.


![image](https://user-images.githubusercontent.com/40387703/173768307-245cec5e-56bd-40bb-ba5e-6d312e7d9255.png)
