### ISSUE TITLE
Revisar tots els camps JAVA dels Beans de BBDD que no estan normalitzats java

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#69]
Editar camps java amb GenApp i posar els camps en nomenclatura java. Regenerar i arreglar errors de compilació.

Exemple de canvis:
idiomadoc => idiomaDoc
destinatarinif => destinatariNif
...

**Comment by ptrias-fundaciobit** [comment]
Solucionat
