### ISSUE TITLE
Revisar Traduccions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#71]
Aquí es mostra una traducció que no existeix. Arreglar-la i revisar si hi ha més codis sense traducció.

![imagen](https://user-images.githubusercontent.com/17084256/173535853-4bebcc57-da54-413a-8a30-00edbd6aa418.png)

**Comment by ptrias-fundaciobit** [comment]
Corregit: 
![image](https://user-images.githubusercontent.com/95921330/174257423-e1168155-53ea-4798-a17c-f82cf9864086.png)
