### ISSUE TITLE
Revisar errors de propietats, urls i credencials de connexio a PortaFIB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#77]
Revisar errors de propietats, urls i credencials de connexio a PortaFIB. S'ha de fer les següent proves i comprovar que capturen l'error i el mostren de forma controlada i asimilable per l'usuari.

(1) Canviar el nom d'alguna de les propietats de firma async.
(2) Posar una URL de portafib incorrecte (posar un 2 despres del domini)
(3) Posar una credencial incorrecte.

**Comment by fbosch-fundaciobit** [comment]
S'han afegit log.errors amb informació detallada de l'error, i un missatge per l'usuari de que hi ha hagut un error:

![image](https://user-images.githubusercontent.com/40387703/174550847-7b339be2-1e09-4e85-89ad-9e1ef20d9487.png)

**Comment by fbosch-fundaciobit** [comment]
Correcions en el control d'errors:

![image](https://user-images.githubusercontent.com/40387703/174781121-2e4c6ad6-b39a-411f-af7d-4831663536e4.png)
