### ISSUE TITLE
Agafar el perfil de firma de la API de firma, llevar perfil fixe.

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [Fundacio-Bit/enviafib#79]
El sistema de firma actual (PADES), es troba configurat amb un codi fixe a la capa de EJB (PeticioLogicaEJB).

S'ha de configurar perque aquest codi s'obtengui des de la API ApiFirmaAsyncSimple de PortaFIB.

**Comment by fbosch-fundaciobit** [comment]
Afegir aquest codi: 

api = getApiFirmaAsyncSimple();
String perfil = api.getAvailableProfiles(tipusDoc);

El parametre que es passa a "getAvailableProfiles" no ha de ser tipusDoc, s'ha de comprovar que espera aquesta funció per retornar el codi per PADES.

**Comment by ptrias-fundaciobit** [comment]
Solucionat!
