### ISSUE TITLE
Revisar pantalla de Vista de Petició en cada estat

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#83]
Revisar pantalla de Vista de Petició en cada estat. 

(1) Segons cada estat de les Peticions  s'han de mostrar més o manco coses. Per exemple: la captura següent es d'una petició en procés i podriem mostrar moltes més coses com tipus, data inici, idiomes, ....

![imagen](https://user-images.githubusercontent.com/17084256/174997890-9349d968-4b73-41dd-9a04-224faad779c7.png)

(2) Canviar el fons de la icona de View ja que es confon amb el fons de la pàgina

![imagen](https://user-images.githubusercontent.com/17084256/174998428-1f0a66af-1564-465a-80eb-69acc44c3853.png)

**Comment by fbosch-fundaciobit** [comment]
Afegesc una captura amb els ajusts que he trobat que es podrien afegir a la pantalla del llistat de peticions.

![image](https://user-images.githubusercontent.com/40387703/175299474-e3d33861-0ed2-4e55-a886-786a53776472.png)

**Comment by fbosch-fundaciobit** [comment]
Ja es veuen els botons corresponents a cada petició al llistat de peticions, i la informació correcte a la pantalla de visualització d'informació d'una petició de tots els tipus disponibles:

S'ha creat un issue amb un cas pendent.  #104 Si es crea una petició de tipus autofirma i es surt de l'aplicació sense haverla firmada de cualsevol manera que no sigui cancelant, la petició queda amb estat "creada" però unicament pot ser borrada, per tant hauria d'estar amb estat d'error, o esborrarse o no crearse.

![image](https://user-images.githubusercontent.com/40387703/176378094-a2e5e1e1-043a-4433-a7a4-8c7f2d5735ba.png)

![image](https://user-images.githubusercontent.com/40387703/176384472-bc75de67-ee77-43a2-ab0d-fbcf356df43c.png)
