### ISSUE TITLE
Cercar feines pendents d'acabar a la capa EJB

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#86]
S'ha de cercar en el codi cadenes com TODO, XYZ, ZZZ o TRA en la capa de EJB que indiquen alguna tasca pendent i arreglar-la.

**Comment by ptrias-fundaciobit** [comment]
Arreglat

**Comment by anadal-fundaciobit** [comment]
![imagen](https://user-images.githubusercontent.com/17084256/175292325-b6f38726-0ecb-456a-9e01-f78e8c58705a.png)

![imagen](https://user-images.githubusercontent.com/17084256/175292338-26762fc9-edd1-45fd-8858-cce46ba8cc42.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat
