### ISSUE TITLE
Canvis en algunes etiquetes de la taula de Petició

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#88]
(1) Canvis en algunes etiquetes de la taula de Petició

Data de Creació => Creada
Data Final => Finalitzada
Tipus de Petició => Tipus

![imagen](https://user-images.githubusercontent.com/17084256/175225361-4a2914ed-8e19-4b92-8d16-a9b574458a2d.png)

(2) Revisar si altres etiquetes poden ser simplificades "sense" perdre significat.

**Comment by ptrias-fundaciobit** [comment]
Arreglat:
![image](https://user-images.githubusercontent.com/95921330/175255974-bb645756-c5c0-42b0-b35f-652e380ee0e6.png)
