### ISSUE TITLE
Adaptar manual de instal·lació  a les novetats descrites al manual de migració

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#89]
Adaptar manual de instal·lació  a les novetats descrites al manual de migració:

* Noves Propietats
* Altres configuracions
* ...

**Comment by fbosch-fundaciobit** [comment]
S'han afegit les noves propietats, i millorat algunes explicacions. 

![image](https://user-images.githubusercontent.com/40387703/177527788-cd951d2d-74f8-45fd-ad07-eb09229f3a09.png)
