### ISSUE TITLE
Millores en la pàgina de HOME

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#90]
(1) Eliminar la cadena "PAGIAN PUBLICA"
(2) Tenc  la propietat "es.caib.enviafib.development=false" però apareixen entrades a la pàgina com LOGIN ANONIM, Locale, ...
(3) Hi ha vàries pàgines com principal.jsp, home.jsp, homepublic.jsp, ... que no s'utilitzen. Fer revisió de quines NO s'utilitzen i esborrar-les.

![imagen](https://user-images.githubusercontent.com/17084256/175227675-76753961-4c12-4ada-9aec-b7450c3b0397.png)

**Comment by fbosch-fundaciobit** [comment]
- La informació de debug domes es mostra en mode debug.
- Afegida informació de UserInformation a info de debug.
- Arreglada redirecció de la Home. (Ja no falla si es refresca amb f5)
- Eliminades pàgines de Home en desus.

![image](https://user-images.githubusercontent.com/40387703/177324398-66caadd1-a0e8-47de-81f2-0c239b61ef76.png)
