### ISSUE TITLE
Millores en el peu de pàgina

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#91]
(1) Separar el logo de la fundació bit  de la linia (mirar si es pot arreglar també a GenApp)
(2) Fer els camps de telefon, web i email configurable per propietat de sistema (enviafib.properties): si algun camp no existeix o no està definit eliminar la fila de informació.
- es.caib.enviafib.ajuda.email
- es.caib.enviafib.ajuda.web
- es.caib.enviafib.ajuda.telefon

![imagen](https://user-images.githubusercontent.com/17084256/175228522-37574823-c671-4b37-9979-ba8c0dc96bb2.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat:
![image](https://user-images.githubusercontent.com/95921330/176186393-0556ddc5-e4c7-4de8-a2bb-a7f8d89dbc4c.png)
