### ISSUE TITLE
Millores en els menus desplegables de la capçalera

### ISSUE THREAD

**Issue by anadal-fundaciobit** [Fundacio-Bit/enviafib#92]
(1) Separar la icona de l'idiona de l'etiqueta (mirar si es pot arreglar també a GenApp)
![imagen](https://user-images.githubusercontent.com/17084256/175230649-8abac115-29fe-4a4a-af1c-656aa4e5d274.png)

(2.A) CONFIGURACIO: Ha d'apuntar a l'edició de l'usuari
(2.B) SORTIR: Ha de ser opcional a partir d'una propietat de enviafib.properties. Aquesta propietat inclourà una url absoluta o relativa. Si la propietat no existeix o està buida aquesta opció del menú no s'ha de mostrar: 

![imagen](https://user-images.githubusercontent.com/17084256/175230759-5cca1f29-b0db-4cf4-a22e-048f26acc95c.png)

Proposta:
```
<% if (Configuracio.getSortirURL() != null  OR [[EMPTY]]) { %>

   [[ OPCIO SORTIR ]]

<%  }  %>
```

**Comment by ptrias-fundaciobit** [comment]
Solucionat
