### ISSUE TITLE
Definir format del correu de petició finalitzada

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [Fundacio-Bit/enviafib#95]
Definir/millorar format del correu de petició finalitzada

**Comment by fbosch-fundaciobit** [comment]
Format final dels email d'actualització de peticions:

![2022-07-05_12h15_20](https://user-images.githubusercontent.com/40387703/177320123-128132e9-7977-46b6-a3fa-32ea29cb9e90.png)
![2022-07-05_12h15_39](https://user-images.githubusercontent.com/40387703/177320130-a8a30b1a-6c10-4763-9cae-4899fcf659d3.png)
